[project]
name = "market-faker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clickhouse-connect>=0.8.11",
    "faker>=33.1.0",
    "polars>=1.18.0",
    "pyarrow>=18.1.0",
    "pydantic>=2.10.4",
]
